name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint django pylint-django
      - name: Analysing the code with pylint
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pylint --load-plugins pylint_django --django-settings-module=app.settings $(find src -name "*.py")
    # strategy:
    #   matrix:
    #     python-version: ["3.8", "3.9", "3.10"]
    # steps:
    #   - uses: actions/checkout@v4
    #   - name: Set up Python ${{ matrix.python-version }}
    #     uses: actions/setup-python@v3
    #     with:
    #       python-version: ${{ matrix.python-version }}
    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install pylint django pylint-django
    #   - name: Analysing the code with pylint
    #     run: |
    #       export PYTHONPATH=$PYTHONPATH:$(pwd)/src
    #       pylint --load-plugins pylint_django --django-settings-module=app.settings $(find src -name "*.py")
